name: HybridServerAPI
version: ${version}
main: com.github.yyeerai.hybridserverapi.HybridServerAPI
api-version: 1.16
depend:
  - PlaceholderAPI
softdepend:
  - ProtocolLib
  - Vault
  - PlayerPoints
  - NyEconomy