# 带有描述信息的宝可梦照片
sprite:
  name: '&f&l{DISPLAY_NAME}'
  y: '是'
  n: '否'
  lore:
    - '&7╠═ Lv.&e{LEVEL}'
    - '&7╠═ &F▶ &B&L概 要 &F◀'
    - '&7╠ &7[闪光] &F{SHINY} &7[特性] &F{ABILITY}'
    - '&7╠ &7[性格] &F{NATURE} &7[薄荷] &F{MINT_NATURE}'
    - '&7╠ &7[性别] &F{GENDER} &7[体型] &F{GROWTH}'
    - '&7╠ &7[携带] &F{HELD_ITEM} &7[捕捉] &F{POKEBALL}'
    - '&7╠═ &F▶ &B&L属 性 &F◀'
    - '&7╠&7&L血量&3{HP} &7&L攻击&3{ATTACK} &7&L防御&3{DEFENCE}'
    - '&7╠&7&L特攻&3{SPECIAL_ATTACK} &7&L特防&3{SPECIAL_DEFENCE} &7&L速度&3{SPEED}'
    - '&7╠═ &F▶ &B&L个 体 &F◀'
    - '&7╠&7&L血量&3{IV_HP} &7&L攻击&3{IV_ATTACK} &7&L防御&3{IV_DEFENCE}'
    - '&7╠&7&L特攻&3{IV_SPECIAL_ATTACK} &7&L特防&3{IV_SPECIAL_DEFENCE} &7&L速度&3{IV_SPEED}'
    - '&7╠═ &F▶ &B&L努 力 &F◀'
    - '&7╠&7&L血量&3{EV_HP} &7&L攻击&3{EV_ATTACK} &7&L防御&3{EV_DEFENCE}'
    - '&7╠&7&L特攻&3{EV_SPECIAL_ATTACK} &7&L特防&3{EV_SPECIAL_DEFENCE} &7&L速度&3{EV_SPEED}'
    - '&7╠═ &F▶ &B&L王 冠 &F◀'
    - '&7╠&7&L血量&3{HT_HP} &7&L攻击&3{HT_ATTACK} &7&L防御&3{HT_DEFENCE}'
    - '&7╠&7&L特攻&3{HT_SPECIAL_ATTACK} &7&L特防&3{HT_SPECIAL_DEFENCE} &7&L速度&3{HT_SPEED}'
    - '&7╠═ &F▶ &B&L标记 &F◀'
    - '&7╠&7&L能否交易&3{TRADEABLE} &7&L能否繁殖&3{BREEDABLE}'
    - '&7╠═ &F▶ &B&L招 式 &F◀'
    - '&7╠&F{MOVE_1} | {MOVE_2} | {MOVE_3} | {MOVE_4}'
    - ''